apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: "2022-01-08T08:36:34Z"
  labels:
    controller-uid: 2054e5f6-af15-4f8f-919f-8af11e3276bf
    id: awesome-job
    job-name: neb-new-job
  name: neb-new-job
  namespace: neptune
  resourceVersion: "216577"
  uid: 2054e5f6-af15-4f8f-919f-8af11e3276bf
spec:
  backoffLimit: 6
  completions: 3
  parallelism: 2
  selector:
    matchLabels:
      controller-uid: 2054e5f6-af15-4f8f-919f-8af11e3276bf
  template:
    metadata:
      creationTimestamp: null
      labels:
        controller-uid: 2054e5f6-af15-4f8f-919f-8af11e3276bf
        id: awesome-job
        job-name: neb-new-job
    spec:
      containers:
      - command:
        - sh
        - -c
        - sleep 2 && echo done
        image: busybox:1.31.0
        imagePullPolicy: IfNotPresent
        name: neb-new-job-container
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  completionTime: "2022-01-08T08:36:40Z"
  conditions:
  - lastProbeTime: "2022-01-08T08:36:40Z"
    lastTransitionTime: "2022-01-08T08:36:40Z"
    status: "True"
    type: Complete
  startTime: "2022-01-08T08:36:34Z"
  succeeded: 3
